# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
author: Cornelia Rehbein

paginate: 5

permalink: /:categories/:title.

category_dir: _categories
category_blog_dir: _blog
category_projects_dir: _projects

excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
